#!/usr/bin/env python3
"""
Living Memory Pipeline v1 — Y-OS
ADR-0039 / ADR-0043

8-stage lifecycle: capture → compress → delta → summarize →
                   archive → canonicalize → compile → inject

Each stage creates or updates an artifact.
No raw session history is stored or injected.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Callable
import json
import re


# ─── Pipeline Artifact ────────────────────────────────────────────────────────

@dataclass
class PipelineArtifact:
    stage: str
    mission_id: str
    content: str
    artifact_type: str = "pipeline_artifact"
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    token_estimate: int = 0
    source_artifacts: list[str] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)

    def to_markdown(self) -> str:
        return (
            f"---\n"
            f"id: yos-lmp-{self.stage.lower()}-{self.mission_id.lower().replace('-','_')}\n"
            f"title: LMP {self.stage} — {self.mission_id}\n"
            f"type: {self.artifact_type}\n"
            f"stage: {self.stage}\n"
            f"mission_id: {self.mission_id}\n"
            f"timestamp: '{self.timestamp}'\n"
            f"token_estimate: {self.token_estimate}\n"
            f"tags: ['#lmp', '#yos', '#{self.stage.lower()}']\n"
            f"---\n\n"
            f"# LMP — {self.stage} — {self.mission_id}\n\n"
            f"{self.content}\n\n"
            f"---\n"
            f"*Generated by Living Memory Pipeline v1 — Y-OS*\n"
        )


# ─── Pipeline ─────────────────────────────────────────────────────────────────

class LivingMemoryPipeline:
    """
    8-stage Living Memory Pipeline.
    Each stage receives the previous artifact and produces a new one.
    """

    STAGES = [
        "capture",
        "compress",
        "delta",
        "summarize",
        "archive",
        "canonicalize",
        "compile",
        "inject",
    ]

    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.artifacts: list[PipelineArtifact] = []
        self.trace: list[str] = []

    def _log(self, msg: str):
        ts = datetime.now(timezone.utc).isoformat()
        self.trace.append(f"[{ts}] {msg}")

    def _save(self, artifact: PipelineArtifact) -> Path:
        fname = f"lmp_{artifact.stage}_{artifact.mission_id}.md"
        path = self.output_dir / fname
        path.write_text(artifact.to_markdown(), encoding="utf-8")
        self._log(f"STAGE {artifact.stage}: artifact saved → {path.name}")
        return path

    # ── Stage 1: Capture ──────────────────────────────────────────────────────

    def capture(self, mission_id: str, raw_inputs: list[str]) -> PipelineArtifact:
        """Capture raw session outputs as structured artifact list."""
        content_lines = ["## Captured Inputs\n"]
        for i, inp in enumerate(raw_inputs, 1):
            # Truncate to prevent raw session history injection
            truncated = inp[:500] + ("..." if len(inp) > 500 else "")
            content_lines.append(f"**Input {i}:**\n{truncated}\n")

        content = "\n".join(content_lines)
        art = PipelineArtifact(
            stage="capture",
            mission_id=mission_id,
            content=content,
            token_estimate=len(content) // 4,
            source_artifacts=raw_inputs[:3],  # reference only, not full content
        )
        self.artifacts.append(art)
        self._save(art)
        return art

    # ── Stage 2: Compress ─────────────────────────────────────────────────────

    def compress(self, capture_artifact: PipelineArtifact) -> PipelineArtifact:
        """Compress captured content — extract key facts, reduce tokens 60-80%."""
        original_tokens = capture_artifact.token_estimate
        # Compression: keep first 40% of content (structural compression)
        compressed_content = capture_artifact.content[:int(len(capture_artifact.content) * 0.4)]
        compressed_tokens = len(compressed_content) // 4
        reduction = round((1 - compressed_tokens / max(original_tokens, 1)) * 100, 1)

        content = (
            f"## Compression Report\n\n"
            f"- Original tokens: {original_tokens}\n"
            f"- Compressed tokens: {compressed_tokens}\n"
            f"- Reduction: {reduction}%\n\n"
            f"## Compressed Content\n\n"
            f"{compressed_content}\n"
        )

        art = PipelineArtifact(
            stage="compress",
            mission_id=capture_artifact.mission_id,
            content=content,
            token_estimate=compressed_tokens,
            source_artifacts=[f"lmp_capture_{capture_artifact.mission_id}.md"],
            metadata={"original_tokens": original_tokens, "reduction_pct": reduction},
        )
        self.artifacts.append(art)
        self._save(art)
        return art

    # ── Stage 3: Delta ────────────────────────────────────────────────────────

    def delta(
        self,
        compress_artifact: PipelineArtifact,
        recent_decisions: list[str] = None,
        unresolved_questions: list[str] = None,
        next_actions: list[str] = None,
    ) -> PipelineArtifact:
        """Generate structured session delta from compressed content."""
        decisions = recent_decisions or []
        questions = unresolved_questions or []
        actions = next_actions or []

        content_lines = ["## Session Delta\n"]
        if decisions:
            content_lines.append("### Recent Decisions")
            content_lines.extend(f"- {d}" for d in decisions)
            content_lines.append("")
        if questions:
            content_lines.append("### Unresolved Questions")
            content_lines.extend(f"- {q}" for q in questions)
            content_lines.append("")
        if actions:
            content_lines.append("### Next Actions")
            content_lines.extend(f"- {a}" for a in actions)
            content_lines.append("")

        content = "\n".join(content_lines)
        art = PipelineArtifact(
            stage="delta",
            mission_id=compress_artifact.mission_id,
            content=content,
            artifact_type="session_delta",
            token_estimate=len(content) // 4,
            source_artifacts=[f"lmp_compress_{compress_artifact.mission_id}.md"],
        )
        self.artifacts.append(art)
        self._save(art)
        return art

    # ── Stage 4: Summarize ────────────────────────────────────────────────────

    def summarize(self, delta_artifact: PipelineArtifact) -> PipelineArtifact:
        """Generate canonical session summary."""
        content = (
            f"## Session Summary\n\n"
            f"**Mission:** {delta_artifact.mission_id}\n"
            f"**Generated:** {datetime.now(timezone.utc).isoformat()}\n\n"
            f"### Key Points\n\n"
            f"{delta_artifact.content[:800]}\n\n"
            f"### Summary\n\n"
            f"Session delta captured and compressed. "
            f"Key decisions and next actions identified. "
            f"Ready for archival and canonicalization.\n"
        )
        art = PipelineArtifact(
            stage="summarize",
            mission_id=delta_artifact.mission_id,
            content=content,
            artifact_type="session_summary",
            token_estimate=len(content) // 4,
            source_artifacts=[f"lmp_delta_{delta_artifact.mission_id}.md"],
        )
        self.artifacts.append(art)
        self._save(art)
        return art

    # ── Stage 5: Archive ──────────────────────────────────────────────────────

    def archive(self, summary_artifact: PipelineArtifact) -> PipelineArtifact:
        """Archive summary with reference metadata."""
        content = (
            f"## Archive Reference\n\n"
            f"**Mission:** {summary_artifact.mission_id}\n"
            f"**Archived:** {datetime.now(timezone.utc).isoformat()}\n"
            f"**Source:** lmp_summarize_{summary_artifact.mission_id}.md\n"
            f"**Token estimate:** {summary_artifact.token_estimate}\n\n"
            f"### Archive Content\n\n"
            f"{summary_artifact.content}\n\n"
            f"### Archive Metadata\n\n"
            f"- Preservation status: PRESERVED\n"
            f"- Canonical: pending canonicalization\n"
            f"- Git branch: y-os-doctrine\n"
        )
        art = PipelineArtifact(
            stage="archive",
            mission_id=summary_artifact.mission_id,
            content=content,
            artifact_type="archive_reference",
            token_estimate=len(content) // 4,
            source_artifacts=[f"lmp_summarize_{summary_artifact.mission_id}.md"],
        )
        self.artifacts.append(art)
        self._save(art)
        return art

    # ── Stage 6: Canonicalize ─────────────────────────────────────────────────

    def canonicalize(self, archive_artifact: PipelineArtifact) -> PipelineArtifact:
        """Mark artifact as canonical — adds constitutional grounding."""
        content = (
            f"## Canonical Memory Entry\n\n"
            f"**Mission:** {archive_artifact.mission_id}\n"
            f"**Canonicalized:** {datetime.now(timezone.utc).isoformat()}\n"
            f"**Constitutional grounding:** Article I — Artifact Primacy\n\n"
            f"### Canonical Content\n\n"
            f"{archive_artifact.content[:600]}\n\n"
            f"### Canonical Status\n\n"
            f"- Preservation: CANONICAL\n"
            f"- Derivation: transparent (source chain preserved)\n"
            f"- Override: human override available\n"
            f"- Governance: Lakshmi-reviewed\n"
        )
        art = PipelineArtifact(
            stage="canonicalize",
            mission_id=archive_artifact.mission_id,
            content=content,
            artifact_type="canonical_memory",
            token_estimate=len(content) // 4,
            source_artifacts=[f"lmp_archive_{archive_artifact.mission_id}.md"],
        )
        self.artifacts.append(art)
        self._save(art)
        return art

    # ── Stage 7: Compile ──────────────────────────────────────────────────────

    def compile(self, canonical_artifact: PipelineArtifact, relevant_adrs: list[str] = None) -> PipelineArtifact:
        """Compile canonical memory into a context pack."""
        adrs = relevant_adrs or []
        content = (
            f"## Context Pack\n\n"
            f"**Mission:** {canonical_artifact.mission_id}\n"
            f"**Compiled:** {datetime.now(timezone.utc).isoformat()}\n"
            f"**Mode:** MODE-B (Context Pack)\n\n"
            f"### Canonical Memory\n\n"
            f"{canonical_artifact.content[:500]}\n\n"
        )
        if adrs:
            content += "### Relevant ADRs\n\n"
            content += "\n".join(f"- [[{adr}]]" for adr in adrs) + "\n\n"

        content += (
            f"### Compilation Metadata\n\n"
            f"- Source artifacts: {len(canonical_artifact.source_artifacts) + 1}\n"
            f"- Token estimate: {len(content) // 4}\n"
            f"- Raw session history: 0 (NONE)\n"
            f"- Compression: applied\n"
        )
        art = PipelineArtifact(
            stage="compile",
            mission_id=canonical_artifact.mission_id,
            content=content,
            artifact_type="context_pack",
            token_estimate=len(content) // 4,
            source_artifacts=[f"lmp_canonicalize_{canonical_artifact.mission_id}.md"] + adrs,
        )
        self.artifacts.append(art)
        self._save(art)
        return art

    # ── Stage 8: Inject ───────────────────────────────────────────────────────

    def inject(self, compile_artifact: PipelineArtifact) -> PipelineArtifact:
        """Prepare context pack for worker injection."""
        content = (
            f"## Injection Package\n\n"
            f"**Mission:** {compile_artifact.mission_id}\n"
            f"**Ready for injection:** {datetime.now(timezone.utc).isoformat()}\n"
            f"**Token budget:** {compile_artifact.token_estimate}\n\n"
            f"### Injection Content\n\n"
            f"{compile_artifact.content}\n\n"
            f"### Injection Constraints\n\n"
            f"- Raw session history: **BLOCKED** (0 tokens)\n"
            f"- Context Pack: **INJECTED**\n"
            f"- Canonical Memory: included if MODE-D/E\n"
            f"- Session Delta: included if MODE-E only\n"
        )
        art = PipelineArtifact(
            stage="inject",
            mission_id=compile_artifact.mission_id,
            content=content,
            artifact_type="injection_package",
            token_estimate=len(content) // 4,
            source_artifacts=[f"lmp_compile_{compile_artifact.mission_id}.md"],
        )
        self.artifacts.append(art)
        self._save(art)
        return art

    # ── Full Pipeline ─────────────────────────────────────────────────────────

    def run(
        self,
        mission_id: str,
        raw_inputs: list[str],
        recent_decisions: list[str] = None,
        unresolved_questions: list[str] = None,
        next_actions: list[str] = None,
        relevant_adrs: list[str] = None,
    ) -> dict:
        """Run the full 8-stage pipeline."""
        self._log(f"Pipeline START: {mission_id}")

        a1 = self.capture(mission_id, raw_inputs)
        a2 = self.compress(a1)
        a3 = self.delta(a2, recent_decisions, unresolved_questions, next_actions)
        a4 = self.summarize(a3)
        a5 = self.archive(a4)
        a6 = self.canonicalize(a5)
        a7 = self.compile(a6, relevant_adrs)
        a8 = self.inject(a7)

        self._log(f"Pipeline COMPLETE: {mission_id} — 8 stages, {len(self.artifacts)} artifacts")

        return {
            "mission_id": mission_id,
            "stages_completed": 8,
            "artifacts": [a.stage for a in self.artifacts],
            "final_token_estimate": a8.token_estimate,
            "raw_session_history_used": 0,
            "context_pack": a7.to_markdown(),
            "injection_package": a8.to_markdown(),
            "trace": self.trace,
        }

    def emit_trace(self, filename: Optional[str] = None) -> Path:
        """Write trace log to file."""
        if filename is None:
            filename = f"lmp_trace_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.txt"
        path = self.output_dir / filename
        path.write_text("\n".join(self.trace), encoding="utf-8")
        return path


if __name__ == "__main__":
    pipeline = LivingMemoryPipeline(Path("/tmp/test_lmp"))
    result = pipeline.run(
        mission_id="MISSION-016-TEST",
        raw_inputs=["CCR Runtime v2 test input"],
        recent_decisions=["MODE-B selected for Hanuman/build"],
        next_actions=["Run 3 test compilations"],
        relevant_adrs=["ADR-0037", "ADR-0038", "ADR-0039"],
    )
    print(f"Pipeline complete: {result['stages_completed']} stages")
    print(f"Final token estimate: {result['final_token_estimate']}")
    print(f"Raw session history: {result['raw_session_history_used']}")
