#!/usr/bin/env python3
"""
Session Delta Engine v1 — Y-OS
ADR-0038 / ADR-0043

Generates, appends, compresses, and emits structured session deltas.
No raw session history is stored or injected.
"""

from __future__ import annotations
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
import json
import re


# ─── Delta Schema ─────────────────────────────────────────────────────────────

@dataclass
class SessionDelta:
    mission_id: str
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    recent_decisions: list[str] = field(default_factory=list)
    unresolved_questions: list[str] = field(default_factory=list)
    open_loops: list[str] = field(default_factory=list)
    state_changes: list[str] = field(default_factory=list)
    user_preferences: list[str] = field(default_factory=list)
    temporary_context: list[str] = field(default_factory=list)
    next_actions: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, ensure_ascii=False)

    def to_markdown(self) -> str:
        lines = [
            f"---",
            f"id: yos-session-delta-{self.mission_id.lower().replace('-', '_')}",
            f"title: Session Delta — {self.mission_id}",
            f"type: session_delta",
            f"mission_id: {self.mission_id}",
            f"timestamp: '{self.timestamp}'",
            f"tags: ['#session-delta', '#yos', '#memory']",
            f"---",
            f"",
            f"# Session Delta — {self.mission_id}",
            f"",
            f"**Timestamp:** {self.timestamp}",
            f"",
        ]

        def section(title, items):
            if items:
                lines.append(f"## {title}")
                for item in items:
                    lines.append(f"- {item}")
                lines.append("")

        section("Recent Decisions", self.recent_decisions)
        section("Unresolved Questions", self.unresolved_questions)
        section("Open Loops", self.open_loops)
        section("State Changes", self.state_changes)
        section("User Preferences", self.user_preferences)
        section("Temporary Context", self.temporary_context)
        section("Next Actions", self.next_actions)

        lines.append("---")
        lines.append("*Generated by Session Delta Engine v1 — Y-OS*")
        return "\n".join(lines)

    def token_estimate(self) -> int:
        """Rough token estimate (4 chars ≈ 1 token)."""
        return len(self.to_markdown()) // 4


# ─── Delta Engine ─────────────────────────────────────────────────────────────

class SessionDeltaEngine:
    """Manages session deltas: append, compress, summarize, emit."""

    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self._deltas: list[SessionDelta] = []

    def create_delta(self, mission_id: str, **kwargs) -> SessionDelta:
        """Create a new delta and append to stack."""
        delta = SessionDelta(mission_id=mission_id, **kwargs)
        self._deltas.append(delta)
        return delta

    def append_delta(self, delta: SessionDelta) -> None:
        """Append an existing delta to the stack."""
        self._deltas.append(delta)

    def compress(self) -> SessionDelta:
        """Compress all deltas into a single merged delta."""
        if not self._deltas:
            raise ValueError("No deltas to compress.")

        mission_id = self._deltas[-1].mission_id
        merged = SessionDelta(mission_id=f"{mission_id}-COMPRESSED")

        seen = {
            "recent_decisions": set(),
            "unresolved_questions": set(),
            "open_loops": set(),
            "state_changes": set(),
            "user_preferences": set(),
            "temporary_context": set(),
            "next_actions": set(),
        }

        for delta in self._deltas:
            for field_name in seen:
                for item in getattr(delta, field_name):
                    if item not in seen[field_name]:
                        seen[field_name].add(item)
                        getattr(merged, field_name).append(item)

        return merged

    def summarize(self) -> str:
        """Generate a plain-text session summary."""
        if not self._deltas:
            return "No deltas available."

        compressed = self.compress()
        lines = [
            f"# Session Summary — {compressed.mission_id}",
            f"",
            f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
            f"**Deltas merged:** {len(self._deltas)}",
            f"",
        ]

        if compressed.recent_decisions:
            lines.append("## Key Decisions")
            for d in compressed.recent_decisions[:5]:
                lines.append(f"- {d}")
            lines.append("")

        if compressed.unresolved_questions:
            lines.append("## Unresolved Questions")
            for q in compressed.unresolved_questions[:5]:
                lines.append(f"- {q}")
            lines.append("")

        if compressed.next_actions:
            lines.append("## Next Actions")
            for a in compressed.next_actions[:5]:
                lines.append(f"- {a}")
            lines.append("")

        return "\n".join(lines)

    def emit_delta(self, delta: SessionDelta, filename: Optional[str] = None) -> Path:
        """Write delta to Markdown file."""
        if filename is None:
            ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            filename = f"session_delta_{delta.mission_id}_{ts}.md"
        path = self.output_dir / filename
        path.write_text(delta.to_markdown(), encoding="utf-8")
        return path

    def emit_summary(self, filename: Optional[str] = None) -> Path:
        """Write session summary to Markdown file."""
        if filename is None:
            ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            filename = f"session_summary_{ts}.md"
        path = self.output_dir / filename
        path.write_text(self.summarize(), encoding="utf-8")
        return path

    def emit_json(self, delta: SessionDelta, filename: Optional[str] = None) -> Path:
        """Write delta to JSON file."""
        if filename is None:
            ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            filename = f"session_delta_{delta.mission_id}_{ts}.json"
        path = self.output_dir / filename
        path.write_text(delta.to_json(), encoding="utf-8")
        return path


if __name__ == "__main__":
    engine = SessionDeltaEngine(Path("/tmp/test_deltas"))
    d = engine.create_delta(
        "MISSION-016-TEST",
        recent_decisions=["Selected MODE-E for Saraswati/learning"],
        unresolved_questions=["Should KGC v3 include body rewriting?"],
        next_actions=["Implement CCR Runtime v2 tests"],
    )
    p = engine.emit_delta(d, "test_delta.md")
    print(f"Delta emitted: {p}")
    print(d.to_markdown()[:200])
