#!/usr/bin/env python3
"""
Module 6: Strategic Memory Engine v1 — Y-OS MISSION-025
Tracks: accepted, rejected, implemented recommendations + outcomes.
Enables strategic learning across sessions.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum


class DecisionStatus(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    IMPLEMENTED = "IMPLEMENTED"
    DEFERRED = "DEFERRED"


@dataclass
class StrategicMemoryEntry:
    recommendation_id: str
    title: str
    status: DecisionStatus
    decided_at: str
    decided_by: str
    rationale: str
    outcome: str
    mission_implemented: str
    impact_realized: str

    def to_dict(self) -> dict:
        return {
            "recommendation_id": self.recommendation_id,
            "title": self.title,
            "status": self.status.value,
            "decided_at": self.decided_at,
            "decided_by": self.decided_by,
            "rationale": self.rationale,
            "outcome": self.outcome,
            "mission_implemented": self.mission_implemented,
            "impact_realized": self.impact_realized,
        }


# Seed with historical decisions (from completed missions)
HISTORICAL_DECISIONS: list[StrategicMemoryEntry] = [
    StrategicMemoryEntry(
        "HIST-001", "Build Knowledge Graph Compiler (KGC v1)",
        DecisionStatus.IMPLEMENTED, "2025-08-01", "CEO/Yannick",
        "Corpus was flat archive, not navigable", "PASSED 7/7", "MISSION-013",
        "100% frontmatter, 565 wikilinks, 8 MOCs — EXCEEDED",
    ),
    StrategicMemoryEntry(
        "HIST-002", "Build Cognitive Graph Architecture",
        DecisionStatus.IMPLEMENTED, "2025-08-15", "CEO/Yannick",
        "Graph was document-level, not concept-level", "PASSED 7/7", "MISSION-014",
        "12 concept nodes, 12 typed relationships — MET",
    ),
    StrategicMemoryEntry(
        "HIST-003", "Implement CCR Runtime v2",
        DecisionStatus.IMPLEMENTED, "2025-09-01", "CEO/Yannick",
        "Context injection was manual and untyped", "PASSED 3/3", "MISSION-016",
        "MODE-B/D/E routing, 0 raw history tokens — EXCEEDED",
    ),
    StrategicMemoryEntry(
        "HIST-004", "Diversify LLM Providers",
        DecisionStatus.IMPLEMENTED, "2025-11-01", "CEO/Yannick",
        "73% OpenAI dependency was single-point-of-failure", "PASSED 7/7", "MISSION-023",
        "OpenAI 42.9% / Anthropic 28.6% / Gemini 28.6% — MET",
    ),
    StrategicMemoryEntry(
        "HIST-005", "Build Live Event Bus",
        DecisionStatus.IMPLEMENTED, "2025-11-15", "CEO/Yannick",
        "ODT had no event-driven update mechanism", "PASSED 7/7", "MISSION-022",
        "44 event types, 24 routing rules, DLQ=0 — EXCEEDED",
    ),
]


class StrategicMemoryEngine:
    def __init__(self):
        self.registry: list[StrategicMemoryEntry] = list(HISTORICAL_DECISIONS)
        self.pending: list[StrategicMemoryEntry] = []

    def add_pending(self, rec_id: str, title: str) -> StrategicMemoryEntry:
        entry = StrategicMemoryEntry(
            recommendation_id=rec_id,
            title=title,
            status=DecisionStatus.PENDING,
            decided_at=datetime.now(timezone.utc).isoformat(),
            decided_by="Strategic Engine",
            rationale="Generated by MISSION-025",
            outcome="Pending",
            mission_implemented="TBD",
            impact_realized="TBD",
        )
        self.pending.append(entry)
        self.registry.append(entry)
        return entry

    def accept(self, rec_id: str, rationale: str = "") -> None:
        for e in self.registry:
            if e.recommendation_id == rec_id:
                e.status = DecisionStatus.ACCEPTED
                e.rationale = rationale or e.rationale
                e.decided_at = datetime.now(timezone.utc).isoformat()

    def to_registry(self) -> list[dict]:
        return [e.to_dict() for e in self.registry]

    def summary(self) -> dict:
        by_status = {}
        for e in self.registry:
            by_status.setdefault(e.status.value, 0)
            by_status[e.status.value] += 1
        return {
            "total": len(self.registry),
            "by_status": by_status,
            "implemented": [e.recommendation_id for e in self.registry if e.status == DecisionStatus.IMPLEMENTED],
            "pending": [e.recommendation_id for e in self.registry if e.status == DecisionStatus.PENDING],
        }
